Models/Profiles.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Dejtinghemsida.Models
{
    public class Profiles
    {
    }
}

Controllers/EntryApiController.cs
using Dejtinghemsida.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using HttpDeleteAttribute = System.Web.Http.HttpDeleteAttribute;
using HttpPostAttribute = System.Web.Mvc.HttpPostAttribute;

namespace Dejtinghemsida.Controllers
{
    public class EntryApiController : Controller
    {
        [HttpPost]
        public void Post([FromBody] Entry _entry)
        {
            using (var _context = new ApplicationDbContext())
            {
                _context.Entries.Add(_entry);
                _context.SaveChanges();
            }
        }

        [HttpDelete]
        public void DeleteFromDb([FromBody] Entry _entry)
        {
            using (var _context = new ApplicationDbContext())
            {
                var entry = _context.Entries.Single(m => m.Id == _entry.Id);
                _context.Entries.Remove(entry);
                _context.SaveChanges();
            }
        }
    }
}

Controllers/ProfilesController.cs
using Dejtinghemsida.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dejtinghemsida.Controllers
{
   
        [Authorize]
        public class ProfilesController : Controller
        {
            private ApplicationDbContext _context;

          
            public ProfilesController()
            {
                _context = new ApplicationDbContext();
            }

            public ApplicationUser GetUserByName(string name)
            {
                var appUser = _context.Users.Single(u => u.UserName == name);

                foreach (var entry in _context.Entries)
                {
                    if (entry.RecipientId == appUser.Id)
                    {
                        appUser.Inlägg.Add(entry);
                    }
                }
                return appUser;
            }

            public ActionResult Update(EditYourProfileViewModel LoggedInUser)
            {
                var UserToChange = GetUserByName(User.Identity.Name);

                LoggedInUser.CurrentUser.UserName = UserToChange.UserName;

                var user = _context.Users.SingleOrDefault(u => u.UserName == UserToChange.UserName);

                user.Förnamn = LoggedInUser.CurrentUser.Förnamn.Substring(0, 1).ToUpper() + LoggedInUser.CurrentUser.Förnamn.Substring(1).ToLower();
                user.Efternamn = LoggedInUser.CurrentUser.Efternamn.Substring(0, 1).ToUpper() + LoggedInUser.CurrentUser.Efternamn.Substring(1).ToLower();
                user.Sysselsättning = LoggedInUser.CurrentUser.Sysselsättning;
                user.Kön = LoggedInUser.CurrentUser.Kön;
                user.Ålder = LoggedInUser.CurrentUser.Ålder;

                _context.SaveChanges();
                return RedirectToAction("YourProfile");
            }

            public ActionResult ChangeProfilePicture([Bind(Exclude = "UserPhoto")] ApplicationUser LoggedInUser)
            {

                var UserToChange = GetUserByName(User.Identity.Name);
                LoggedInUser.UserName = UserToChange.UserName;
                var user = _context.Users.SingleOrDefault(u => u.UserName == UserToChange.UserName);

                byte[] imageData = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["UserPhoto"];

                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        imageData = binary.ReadBytes(poImgFile.ContentLength);
                    }
                }

                user.UserPhoto = imageData;

                _context.SaveChanges();
                return RedirectToAction("YourProfile");
            }

            public ActionResult EditYourProfile(EditYourProfileViewModel model)
            {

                var user = GetUserByName(User.Identity.Name);
                var intressen = _context.Intressen.ToList();
                model.CurrentUser = new ApplicationUser();

                model.CurrentUser.Ålder = user.Ålder;
                model.CurrentUser.Förnamn = user.Förnamn;
                model.CurrentUser.Efternamn = user.Efternamn;
                model.CurrentUser.Sysselsättning = user.Sysselsättning;
                model.CurrentUser.Kön = user.Kön;

                model.Requests = new List<ApplicationUser>();
                var allFriendRequests = _context.Friendrequests.ToList();

                foreach (var u in allFriendRequests)
                {
                    if (model.CurrentUser.Id == u.FriendId)
                    {
                        model.Requests.Add(GetOtherUser(u.UserId));
                    }
                }
                return View(model);
            }

            protected override void Dispose(bool disposing)
            {
                _context.Dispose();
            }

            public ActionResult MyMatches(MyMatchesViewModel model)
            {
                model.Requests = new List<ApplicationUser>();
                var allFriendRequests = _context.Friendrequests.ToList();
                var user = GetUserByName(User.Identity.Name);

                foreach (var u in allFriendRequests)
                {
                    if (user.Id == u.FriendId)
                    {
                        model.Requests.Add(GetOtherUser(u.UserId));
                    }
                }

                return View(model);
            }

            public ActionResult PotentialMatches(PotentialMatchesViewModel model)
            {
                model.Requests = new List<ApplicationUser>();
                var allFriendRequests = _context.Friendrequests.ToList();
                var user = GetUserByName(User.Identity.Name);

                foreach (var u in allFriendRequests)
                {
                    if (user.Id == u.FriendId)
                    {
                        model.Requests.Add(GetOtherUser(u.UserId));
                    }
                }

                return View(model);
            }

            public ActionResult OtherProfile(OtherProfileViewModel model, String Id)
            {
                var otherUser = GetOtherUser(Id);
                model.CurrentUser = new ApplicationUser();

                model.CurrentUser.UserName = otherUser.UserName;
                var you = GetUserByName(User.Identity.Name);
                var user = _context.Users.Single(u => u.UserName == model.CurrentUser.UserName);

                model.CurrentUser.Id = user.Id;
                model.CurrentUser.Förnamn = user.Förnamn;
                model.CurrentUser.Efternamn = user.Efternamn;
                model.CurrentUser.Ålder = user.Ålder;
                model.CurrentUser.Kön = user.Kön;
                model.CurrentUser.Sysselsättning = user.Sysselsättning;
                model.CurrentUser.UserName = user.UserName;
                foreach (var entry in _context.Entries)
                {
                    if (model.CurrentUser.Id == entry.RecipientId)
                    {
                        model.CurrentUser.Inlägg.Add(entry);
                    }
                }

                model.Requests = new List<ApplicationUser>();
                var allFriendRequests = _context.Friendrequests.ToList();

                foreach (var u in allFriendRequests)
                {
                    if (you.Id == u.FriendId)
                    {
                        model.Requests.Add(GetOtherUser(u.UserId));
                    }
                }



                return View(model);
            }

            public ActionResult YourProfile(ProfileViewModel model)
            {
                var user = GetUserByName(User.Identity.Name);
                var allFriends = _context.Friends.ToList();
                model.CurrentUser = user;
                model.CurrentUser.Id = user.Id;
                model.CurrentUser.Förnamn = user.Förnamn;
                model.CurrentUser.Efternamn = user.Efternamn;
                model.CurrentUser.Ålder = user.Ålder;
                model.CurrentUser.Kön = user.Kön;
                model.CurrentUser.Id = user.Id;
                model.CurrentUser.Sysselsättning = user.Sysselsättning;
                model.CurrentUser.UserPhoto = user.UserPhoto;
                model.CurrentUser.Inlägg = user.Inlägg;
                model.Friends = new List<ApplicationUser>();

                foreach (var f in allFriends)
                {
                    if (f.UserId == user.Id)
                    {
                        model.Friends.Add(GetOtherUser(f.FriendId));
                    }
                    if (f.FriendId == user.Id)
                    {
                        model.Friends.Add(GetOtherUser(f.UserId));
                    }
                }

                model.WallEntrys = new List<Entry>();

                foreach (var entry in _context.Entries)
                {
                    if (entry.RecipientId == user.Id)
                    {
                        model.WallEntrys.Add(entry);
                    }
                }

                model.Requests = new List<ApplicationUser>();
                var allFriendRequests = _context.Friendrequests.ToList();

                foreach (var u in allFriendRequests)
                {
                    if (user.Id == u.FriendId)
                    {
                        model.Requests.Add(GetOtherUser(u.UserId));
                    }
                }


                return View(model);
            }



            public FileContentResult UserPhotos()
            {
                string userId = User.Identity.GetUserId();
                var LoggedInUser = GetUserByName(User.Identity.Name);
                if (LoggedInUser.UserPhoto.Length == 0)
                {
                    string fileName = HttpContext.Server.MapPath(@"~/Images/hejhej.jpg");
                    byte[] imageData = null;
                    FileInfo fileInfo = new FileInfo(fileName);
                    long imageFileLength = fileInfo.Length;
                    FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                    BinaryReader br = new BinaryReader(fs);
                    imageData = br.ReadBytes((int)imageFileLength);

                    return File(imageData, "image/png");
                }

                var bdUsers = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
                var userImage = bdUsers.Users.Where(u => u.Id == userId).FirstOrDefault();

                return new FileContentResult(userImage.UserPhoto, "image/jpeg");
            }

            public FileContentResult OtherUsersPhoto(string Id)
            {
                string userId = Id;
                var OtherUser = GetOtherUser(userId);

Views/Profiles/EditYourProfile.cshtml
@model Dejtinghemsida.Models.EditYourProfileViewModel
@using Dejtinghemsida.Models

@{

    ViewBag.Title = "Redigera Profil";
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";
}

<h2>Redigera din profil</h2>
<div class="container-fluid">


    <div class="row" style="padding-left: 300px;">

        @using (Html.BeginForm("Update", "Profiles"))
        {

            <div class="col">
                @Html.ValidationSummary("", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.CurrentUser.Förnamn)
                    @Html.TextBoxFor(m => m.CurrentUser.Förnamn, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.CurrentUser.Efternamn)
                    @Html.TextBoxFor(m => m.CurrentUser.Efternamn, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.CurrentUser.Kön)
                    @Html.DropDownListFor(m => m.CurrentUser.Kön, new SelectList(Enum.GetValues(typeof(ApplicationUser.Gender))), " ", new { @class = "form-control" })
                </div>

            </div>

            <div class="col">

                <div class="form-group">
                    @Html.LabelFor(m => m.CurrentUser.Sysselsättning)
                    @Html.TextBoxFor(m => m.CurrentUser.Sysselsättning, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.CurrentUser.Ålder)
                    @Html.TextBoxFor(m => m.CurrentUser.Ålder, new { @class = "form-control" })

                </div>

            </div>
            <button type="submit" class="btn btn-primary btn-primary">Spara</button>
        }

        <div class="form-group">
           

            @using (Html.BeginForm("ChangeProfilePicture", "Profiles", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.LabelFor(m => m.UserPhoto)

                <div class="align-content-lg-start">
                    <input type="file" name="UserPhoto" id="fileUpload" accept=".png,.jpg,.jpeg,.gif,.tif" , new {@class="form-control" } />
                </div>

                <div class="align-content-lg-start">
                    <button type="submit" class="btn btn-primary btn-sm">Byt</button>
                </div>
            }
        </div>
    </div>
</div>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Profiles/FriendRequests.cshtml
@model Dejtinghemsida.Models.PendingFriendRequests
@{
    ViewBag.Title = "Vänförfrågningar";
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";
}

<h2>Vänförfrågningar</h2>
<table class="table table-hover">
    <thead>
        @foreach (var friend in Model.Requests)
        {
            var friendId = friend.Id;
            <tr>
                <th scope="col"><a href="/Profiles/OtherProfile/@friendId"> @friend.Förnamn @friend.Efternamn</a></th>
                <th scope="col"> <button type="button" value="Create" onclick="location.href='@Url.Action("AcceptFriend", "Profiles", new { Id = friendId })'" class="btn btn-primary btn-sm">Lägg till</button></th>
                <th scope="col"> <button type="button" value="Create" onclick="location.href='@Url.Action("IgnoreFriend", "Profiles", new { Id = friendId })'" class="btn btn-primary btn-sm">Ta bort</button></th>
            </tr>
        }
    </thead>
</table>

Views/Profiles/MyMatches.cshtml
@model Dejtinghemsida.Models.MyMatchesViewModel
@{
    ViewBag.Title = "Mina Matchningar";
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";
}

<div class="jumbotron">
    <h1 class="display-3">Matchningar</h1>
    <p class="lead">Dina matchningar!</p>
    <hr class="h1">
</div>

<div class="row">

</div>
<div class="card mb-3 mx-1 col-sm">
    <h5 class="card-header">Användarnamn</h5>
    <div class="card-body">
        <h5 class="card-title">Förnamn</h5>
        <h6 class="card-subtitle text-muted">Kön, Ålder</h6>
    </div>
    <img style="height: 200px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">
    <div class="card-body">
        <p class="card-text">

        </p>
    </div>
    <div class="card-body">
        <a href="#" class="card-link">Besök min profil!</a>
    </div>
    <div class="card-footer text-muted">
        1 days ago
    </div>
</div>
<div class="card mb-3 mx-1 col-sm">
    <h5 class="card-header">Användarnamn</h5>
    <div class="card-body">
        <h5 class="card-title">Förnamn</h5>
        <h6 class="card-subtitle text-muted">Kön, Ålder</h6>
    </div>
    <img style="height: 200px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image">
    <div class="card-body">
        <p class="card-text">

        </p>
    </div>
    <div class="card-body">
        <a href="#" class="card-link">Besök min profil!</a>
    </div>
    <div class="card-footer text-muted">
        6 days ago
    </div>
</div>

Views/Profiles/OtherProfile.cshtml
@{
    ViewBag.Title = "OtherProfile";
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";

}
@using Microsoft.AspNet.Identity;
@using Dejtinghemsida.Controllers
@model Dejtinghemsida.Models.OtherProfileViewModel

<div class="row" style="padding-top: 25px">

    <div class="col-5">

        <div class="card mb-3">
            <h3 class="card-header">@Html.DisplayFor(m => m.CurrentUser.Förnamn) @Html.DisplayFor(m => m.CurrentUser.Efternamn)</h3>
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayFor(m => m.CurrentUser.Kön), @Html.DisplayFor(m => m.CurrentUser.Ålder)</h5>

            </div>
            <img src="@Url.Action("OtherUsersPhoto", "Profiles", new { Id = Model.CurrentUser.Id} )" style="width:250px;height:300px; background: #808080;
                margin: auto;
                -moz-border-radius: 60px;
                border-radius: 100px;
                padding: 3px;
                object-fit:cover" />
            <div class="card-body">
                <p>@Html.DisplayFor(m => m.CurrentUser.Sysselsättning)</p>
                <p>@Html.DisplayFor(m => m.CurrentUser.Intressen)</p>
            </div>

            <div class="card-body">
                <a href="#" class="card-link">Passar vi?</a>
                <a href="@Url.Action("AddFriend", "Profiles", new { Id = Model.CurrentUser.Id })" class="card-link" style="float:right">Skicka vänförfrågan</a>
            </div>
            <div class="card-footer text-muted">
                Senast inloggad: 1 days ago
            </div>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <h3>Vägg</h3>
            <textarea class="form-control" id="entryCont" rows="3" style="margin-top: 0px; margin-bottom: 0px; height: 103px;" placeholder="Skriv din text här.."></textarea>
        </div>

        <button type="button" class="btn btn-primary btn-sm" style="margin-bottom: 20px" id="send">Publicera</button>
        <div id="inlägg">
            @foreach (var entry in Model.CurrentUser.Inlägg.Reverse())
            {

                var currentUser = ((ProfilesController)this.ViewContext.Controller).GetUserByName(User.Identity.Name);
                var author = ((ProfilesController)this.ViewContext.Controller).GetOtherUser(entry.AuthorId);

                if (currentUser.Id == author.Id)
                {

                    <div class="card border-light mb-3" style="max-width: 20rem; ">
                        <div class="card-header"><a href="@Url.Action("YourProfile", "Profiles", new { id = entry.AuthorId })" class="card-link">@author.Förnamn @author.Efternamn</a></div>
                        <div class="card-body">

                            <p class="card-text">@entry.Content</p>
                        </div>
                    </div>
                }
                else
                {
                    <div class="card border-light mb-3" style="max-width: 20rem; ">
                        <div class="card-header"><a href="@Url.Action("AndraProfiler", "Profiles", new { id = entry.AuthorId })" class="card-link">@author.Förnamn @author.Efternamn</a></div>
                        <div class="card-body">

                            <p class="card-text">@entry.Content</p>
                        </div>
                    </div>
                }
            }
        </div>
    </div>


</div>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>
$('#send').on('click', function () {

    var repId = "@Model.CurrentUser.Id";
    var authId = "@HttpContext.Current.User.Identity.GetUserId()";
    var cont = $('#entryCont').val();
    var objEntry = {
        Content: cont,
        AuthorId: authId,
        RecipientId: repId
    }
    var entry = JSON.stringify(objEntry);

    $.ajax({
        type: 'post',
        data: entry,
        dataType: 'JSON',
        contentType: 'application/json; charset=utf-8',
        url: '@Url.Action("Post", "EntryApi", new { httproute = "" })',
        success: function (data) {
            $('entryCont').val('');
            location.reload();

        }
    });


});
</script>

Views/Profiles/SearchView.cshtml
@using Microsoft.AspNet.Identity
@using Dejtinghemsida.Controllers
@model Dejtinghemsida.Models.SearchResultsViewModel


@{
    

    ViewBag.Title = "SearchView";
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";
}

<h3>Resultat</h3>
<table class="table table-hover">
    <thead>
        @foreach (var userHit in Model.Results)
        {

            var currentUser = ((ProfilesController)this.ViewContext.Controller).GetUserByName(User.Identity.Name);
            if (userHit.Id == currentUser.Id)
            {

                <tr>
                    <a href="/Profiles/YourProfile/" class="list-group-item list-group-item-action">
                        @userHit.Förnamn @userHit.Efternamn <p style="float:right">@userHit.UserName</p>
                    </a>
                </tr>
            }
            else
            {
                <a href="/Profiles/OtherProfile/@userHit.Id" class="list-group-item list-group-item-action">
                    @userHit.Förnamn @userHit.Efternamn <p style="float:right">@userHit.UserName</p>
                </a>
            }
        }
    </thead>
</table>

Views/Profiles/YourProfile.cshtml
@using Microsoft.AspNet.Identity
@using Dejtinghemsida.Controllers
@model Dejtinghemsida.Models.ProfileViewModel


@{

    ViewBag.Title = "Min Profil";
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";
}

<div class="row" style="padding-top: 80px">
    <div class="col">
        <h3>Dina Vänner</h3>
        <div class="list-group">
            @foreach (var user in Model.Friends)
            {
                var userId = user.Id;
                <a href="/Profiles/OtherProfile/@userId" class="list-group-item list-group-item-action">
                    @user.Förnamn @user.Efternamn
                </a>
            }

        </div>
        
    </div>

    <div class="col-6">

        <div class="card mb-3">
            <h3 class="card-header">@Html.DisplayFor(m => m.CurrentUser.Förnamn) @Html.DisplayFor(m => m.CurrentUser.Efternamn) </h3>
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayFor(m => m.CurrentUser.Kön), @Html.DisplayFor(m => m.CurrentUser.Ålder)</h5>
            </div>

            <img src="@Url.Action("UserPhotos", "Profiles")" style="width:150px;height:200px; background: #808080;
                margin: auto;
                -moz-border-radius: 60px;
                border-radius: 100px;
                padding: 3px;
                object-fit:cover" />

            <div class="card-body">
                <p><h4>Sysselsättning: </h4></p>
                <p>@Html.DisplayFor(m => m.CurrentUser.Sysselsättning)</p>

                <a href="User/" class="card-link" style="float:right">@Html.ActionLink("Redigera Profil", "EditYourProfile")</a>
            </div>
            <div class="card-footer text-muted">
                Senast inloggad: 1h ago
            </div>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <h3>Inlägg</h3>
            <textarea class="form-control" id="entryCont" rows="3" style="margin-top: 0px; margin-bottom: 0px; height: 200px;" placeholder="Skriv din text här.."></textarea>
        </div>

        <button type="button" class="btn btn-primary btn-sm" style="margin-bottom: 25px" id="send">Publicera</button>
        <div id="inlägg">
            @foreach (var entry in Model.WallEntrys.Reverse())
            {
                var currentUser = ((ProfilesController)this.ViewContext.Controller).GetUserByName(User.Identity.Name);
                var author = ((ProfilesController)this.ViewContext.Controller).GetOtherUser(entry.AuthorId);

                if (currentUser.Id == author.Id)
                {

                    <div class="card border-light mb-3" style="max-width: 20rem; ">
                        <div class="card-header"><a href="@Url.Action("YourProfile", "Profiles", new { id = entry.AuthorId })">@author.Förnamn @author.Efternamn</a><p style="float:right">#<a id="msgId">@entry.Id</a></p></div>
                        <div class="card-body">

                            <p class="card-text" id="cont">@entry.Content</p>
                            <button data-id="@entry.Id" type="button" class="btn btn-primary btn-sm btn-del" style="float:right">Radera Inlägg</button>
                        </div>

                    </div>

                }
                else
                {

                    <div class="card border-light mb-3" style="max-width: 20rem; ">
                        <div class="card-header"><a href="@Url.Action("OtherProfile", "Profiles", new { id = entry.AuthorId })">@author.Förnamn @author.Efternamn</a><p style="float:right">#<a id="msgId">@entry.Id</a></p></div>
                        <div class="card-body">

                            <p class="card-text" id="cont">@entry.Content</p>
                            <button data-id="@entry.Id" type="button" class="btn btn-primary btn-sm btn-del" style="float:right">Radera Inlägg</button>
                        </div>

                    </div>
                }

            }

        </div>
    </div>


</div>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>

    $('#inlägg').on('click', '.btn-del[data-id]', function () {



    var entry = {
        Id: $(this).attr('data-id'),
        Content: $('cont').val()
    };

    console.log(entry.Content);

    $.ajax({
        type: 'DELETE',
        data: JSON.stringify(entry),
        url: '@Url.Action("DeleteFromDb", "EntryApi", new { httproute = "" })',
        contentType: 'application/json',
        dataType: 'JSON',
        success: function (data) {
            location.reload();
        }

    });


});


$('#send').on('click', function () {

    var repId = "@Model.CurrentUser.Id";
    var authId = "@HttpContext.Current.User.Identity.GetUserId()";
    var cont = $('#entryCont').val();
    var objEntry = {
        Content: cont,
        AuthorId: authId,
        RecipientId: repId
    };
    var entry = JSON.stringify(objEntry);

    $.ajax({
        type: 'POST',
        data: entry,
        dataType: 'JSON',
        contentType: 'application/json',
        url: '@Url.Action("Post", "EntryApi", new { httproute = "" } )',
        success: function (data) {
            $('#entryCont').val('');
            location.reload();

        }
    });


});
</script>